import { useState, useEffect } from 'react'

import './Popup.css'
import { Button } from '@/components/shadcn/ui/button'

export const Popup = () => {
  const [count, setCount] = useState(0)
  const link = 'https://github.com/guocaoyi/create-chrome-ext'

  const openDashboard = () => {
    chrome.tabs.create({ url: chrome.runtime.getURL('dashboard.html') })
  }

  const openSidePanel = () => {
    // chrome.runtime.sendMessage({ type: 'OPEN_SIDE_PANEL' })
    // chrome.runtime.sendMessage({ action: 'open_side_panel' })
    chrome.windows.getCurrent({ populate: true }, (window) => {
      ;(chrome as any).sidePanel.open({ windowId: window.id })
    })
  }

  const minus = () => {
    if (count > 0) setCount(count - 1)
  }

  const add = () => setCount(count + 1)

  useEffect(() => {
    chrome.storage.sync.get(['count'], (result) => {
      setCount(result.count || 0)
    })
  }, [])

  useEffect(() => {
    chrome.storage.sync.set({ count })
    chrome.runtime.sendMessage({ type: 'COUNT', count })
  }, [count])

  return (
    <main>
      <h3>Popup Page</h3>
      <div className="calc">
        <button onClick={minus} disabled={count <= 0}>
          -
        </button>
        <label>{count}</label>
        <button onClick={add}>+</button>
      </div>
      <a href={link} target="_blank">
        generated by create-chrome-ext
      </a>
      <Button onClick={openDashboard} className="mt-4">
        Open Dashboard
      </Button>
      <Button onClick={openSidePanel} className="mt-4">
        Open Side Panel 2
      </Button>
    </main>
  )
}

export default Popup
